# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_stack_name', 'get_project_name', 'export']

# %% ../nbs/00_core.ipynb 4
from fastcore.all import *
import pulumi
from typing import Optional, Dict, Any

# %% ../nbs/00_core.ipynb 6
def get_stack_name() -> str:
    "Get current Pulumi stack name"
    return pulumi.get_stack()

# %% ../nbs/00_core.ipynb 7
def get_project_name() -> str:
    "Get current Pulumi project name"
    return pulumi.get_project()

# %% ../nbs/00_core.ipynb 8
def export(key: str, value: Any):
    "Export a value as stack output"
    pulumi.export(key, value)
