# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_env.ipynb.

# %% ../nbs/00_env.ipynb #47ca0195
from __future__ import annotations
import asyncio, inspect, os, sys, threading
from fastcore.all import Path

# %% auto #0
__all__ = ['BUNDLE_ONLY', 'EnvError', 'strip_bundle', 'clean_env', 'venv_env', 'use_extra', 'extra', 'needs_extra', 'EnvStore',
           'env_value']

# %% ../nbs/00_env.ipynb #1e650a43
BUNDLE_ONLY = ('PYTHONHOME', 'PYTHONPATH', 'PYTHONEXECUTABLE', '__PYVENV_LAUNCHER__', 'RESOURCEPATH')

class EnvError(RuntimeError): pass

# %% ../nbs/00_env.ipynb #9d27ac2f
def strip_bundle(env, frozen=None):
    "Return `env` without frozen-host interpreter redirection."
    if not (getattr(sys, 'frozen', False) if frozen is None else frozen): return env
    for name in BUNDLE_ONLY: env.pop(name, None)
    env['PYTHONUTF8'] = '1'
    return env

def clean_env():
    "Return this process's environment without bundle variables."
    return strip_bundle(os.environ.copy(), frozen=True)

# %% ../nbs/00_env.ipynb #4b56c811
def venv_env(python=None, env=None):
    "Return `env` with `python`'s virtual environment prepended to `PATH`; None leaves the environment unchanged."
    env = strip_bundle(dict(os.environ if env is None else env))
    if not python: return env
    bindir = str(Path(python).parent)
    env['VIRTUAL_ENV'] = str(Path(bindir).parent)
    env.pop('UV_PROJECT_ENVIRONMENT', None)
    env['PATH'] = bindir + os.pathsep + env.get('PATH', '')
    env.pop('PYTHONHOME', None)
    return env

# %% ../nbs/00_env.ipynb #54dbd62c
_extra = 'pullup'

def use_extra(name):
    "Name the package every message about the cloud half tells the reader to install."
    global _extra
    _extra = str(name)

def extra(): return _extra

def needs_extra(what): return f'{what}: pip install "{_extra}"'

# %% ../nbs/00_env.ipynb #e34073db
def _dockeasy():
    try: from dockeasy.core import env_get, env_set, secret_get, secret_set
    except ImportError as e:
        raise EnvError(needs_extra('environment values are stored by dockeasy')) from e
    import logging
    logging.getLogger('dotenv.main').setLevel(logging.ERROR)
    return env_get, env_set, secret_get, secret_set

def _call(fn, *args, **kwargs):
    "Call `fn`, awaiting it on its own loop when dockeasy hands back a coroutine."
    value = fn(*args, **kwargs)
    if not inspect.isawaitable(value): return value
    try: asyncio.get_running_loop()
    except RuntimeError: return asyncio.run(value)
    out = []
    def run():
        try: out.append((True, asyncio.run(value)))
        except BaseException as e: out.append((False, e))
    thread = threading.Thread(target=run); thread.start(); thread.join()
    ok, value = out[0]
    if ok: return value
    raise value

# %% ../nbs/00_env.ipynb #9937a32a
class EnvStore:
    "The environment keys one project cares about, read and written through dockeasy."
    def __init__(self, service='fastops', path=None): self.service, self.path = service, path
    def get(self, key, secret=True):
        "One value, from the keychain or the env file, falling back to this process's environment."
        env_get, _set, secret_get, _sset = _dockeasy()
        stored = (_call(secret_get, key, service=self.service, path=self.path) if secret
                  else _call(env_get, key, path=self.path))
        return stored or os.environ.get(key) or ''
    def set(self, key, value, secret=True):
        "Store one value. A secret goes to the keychain as well as the file; a variable does not."
        key = str(key or '').strip()
        if not key: raise EnvError('a key is required')
        if not str(value): raise EnvError(f'{key} needs a value')
        env_get, env_set, secret_get, secret_set = _dockeasy()
        if secret: _call(secret_set, key, str(value), service=self.service, path=self.path)
        else: _call(env_set, key, str(value), path=self.path)
        return {'key': key, 'secret': bool(secret)}
    def unset(self, key):
        "Remove a value from every place `set` put it. Says which places actually held one."
        from dockeasy.core import _FASTOPS_ENV
        from dotenv import unset_key
        key, gone = str(key), []
        try:
            import keyring
            if keyring.get_password(self.service, key) is not None:
                keyring.delete_password(self.service, key)
                gone.append('keychain')
        except Exception: pass
        path = str(self.path or _FASTOPS_ENV)
        try:
            removed, _ = unset_key(path, key)
            if removed: gone.append('env file')
        except Exception: pass
        os.environ.pop(key, None)
        return {'key': key, 'removed': gone}
    def values(self, keys, secret=True):
        "Every key that has a value, as a dict. A key with none is absent rather than empty."
        out = {}
        for k in keys:
            try: v = self.get(k, secret=secret)
            except Exception: v = os.environ.get(k) or ''
            if v: out[k] = v
        return out

# %% ../nbs/00_env.ipynb #55636ab5
def env_value(store, key, default='', secret=False):
    "One value out of an environment store, or `default` when it is unset or unreadable."
    try: return store.get(key, secret=secret) or default
    except Exception: return default
