# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_hetzner.ipynb.

# %% auto 0
__all__ = ['volume', 'network', 'server']

# %% ../nbs/04_hetzner.ipynb 3
from fastcore.all import *
import pulumi
from typing import Optional, List, Dict, Any

# %% ../nbs/04_hetzner.ipynb 5
def _check_hcloud():
    "Check if pulumi-hcloud is installed"
    try:
        import pulumi_hcloud
        return pulumi_hcloud
    except ImportError:
        raise ImportError("pulumi-hcloud not installed. Install with: pip install pulumi-hcloud")

# %% ../nbs/04_hetzner.ipynb 7
def volume(name:str=None, # Volume name
           size:int=10, # Size in GB
           location:str="nbg1", # Location
           **kwargs):
    "Create Hetzner Cloud Volume"
    hcloud = _check_hcloud()
    
    volume_name = name or f"pullup-{pulumi.get_project()}"
    
    vol = hcloud.Volume(volume_name,
        size=size,
        location=location,
        **kwargs)
    
    return vol

# %% ../nbs/04_hetzner.ipynb 9
def network(name:str=None, # Network name
            cidr:str="10.0.0.0/16", # IP range
            **kwargs):
    "Create Hetzner Cloud Network"
    hcloud = _check_hcloud()
    
    network_name = name or f"pullup-{pulumi.get_project()}"
    
    net = hcloud.Network(network_name,
        ip_range=cidr,
        **kwargs)
    
    return net

# %% ../nbs/04_hetzner.ipynb 11
def server(name:str=None, # Server name
           server_type:str="cx11", # Server type
           image:str="ubuntu-22.04", # OS image
           location:str="nbg1", # Location
           **kwargs):
    "Create Hetzner Cloud Server"
    hcloud = _check_hcloud()
    
    server_name = name or f"pullup-{pulumi.get_project()}"
    
    srv = hcloud.Server(server_name,
        server_type=server_type,
        image=image,
        location=location,
        **kwargs)
    
    return srv
