name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  nbdev:
    runs-on: ubuntu-latest
    steps: [uses: AnswerDotAI/workflows/nbdev3-ci@master]
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install --group dev -e .
      - run: pytest -q
